### ISSUE TITLE
Panic on download

### ISSUE THREAD

**Issue by patrikhermansson** [gotd/td#183]
Hi!
There appears to be a regression in v0.26.1, I've started testing this library out on a project and been working fine but when I upgraded to latest version I get a panic when trying to download files. The panic doesnt happen in the download function itself but this is triggered when I begin a download, if I comment out my call to download, receiving messages etc. works just fine. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x537f57a]

goroutine 171 [running]:
github.com/gotd/td/telegram/internal/manager.(*Conn).OnSession(0xc01c21e000, 0x44060bbdaafe45a9, 0xa01a6f8563c2504b, 0xadb5c849c8e82027, 0x9ba0c78becbf1b0b, 0x89fda9395701dbb0, 0x3bfa47bdf85e178e, 0x2863c1e9d6a35250, 0xe640e8c50c0152f6, 0x59bfee9847d544f9, ...)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/telegram/internal/manager/conn.go:89 +0x17a
github.com/gotd/td/mtproto.(*Conn).handleSessionCreated(0xc000358c80, 0xc00019e3a8, 0xe, 0x0)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/mtproto/handle_session_created.go:20 +0x31a
github.com/gotd/td/mtproto.(*Conn).handleMessage(0xc000358c80, 0xc00019e3a8, 0x14, 0x14)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/mtproto/handle_message.go:21 +0x2ca
github.com/gotd/td/mtproto.(*Conn).processContainerMessage(0xc000358c80, 0x6049c96fcdeb0801, 0x1, 0x1c, 0xc0002d2fc0, 0x1c, 0x1c, 0x59e2916, 0x9)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/mtproto/handle_container.go:26 +0x68
github.com/gotd/td/mtproto.(*Conn).handleContainer(0xc000358c80, 0xc00019e330, 0xe, 0x0)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/mtproto/handle_container.go:17 +0x177
github.com/gotd/td/mtproto.(*Conn).handleMessage(0xc000358c80, 0xc00019e330, 0x0, 0x0)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/mtproto/handle_message.go:25 +0x20a
github.com/gotd/td/mtproto.(*Conn).readEncryptedMessages(0xc000358c80, 0x5cbfe08, 0xc01bff1240, 0xc, 0x0)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/mtproto/read.go:172 +0x157
github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1(0x5cbfe08, 0xc01bff1240, 0x0, 0x0)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/internal/tdsync/log_group.go:45 +0x270
github.com/gotd/td/internal/tdsync.(*CancellableGroup).Go.func1(0x0, 0x0)
        /Users/myusername/go/pkg/mod/github.com/gotd/td@v0.26.1/internal/tdsync/cancel_group.go:47 +0x3b
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc01c20d380, 0xc01bfaaa98)
        /Users/myusername/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/myusername/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
exit status 2
make: *** [run] Error 1
```

**Comment by patrikhermansson** [comment]
After looking closer it appears that it's specifically .ToPath() that is the issue. This fails:

`downloader.NewDownloader().Download(c, loc).ToPath(path)`

While this works:
`downloader.NewDownloader().Download(c, loc).Stream(ctx, f)`

So easy to work around.

**Comment by ernado** [comment]
Hey @patrikhermansson, thank you for report!

While we are trying to analyze stack trace, can you please provide a code snippet so we can speed up investigation?

**Comment by ernado** [comment]
We've found problem, fix will be available soon, no code snipped is needed.

**Comment by patrikhermansson** [comment]
Appreciate the quick response and all your work here! I should have included some code, sorry! Great that you already find it but just to clarify, it happens when I call both of these:

`downloader.NewDownloader().Download(c, loc).Stream(ctx, f)`

`downloader.NewDownloader().Download(c, loc).ToPath(ctx, path)`

**Comment by tdakkota** [comment]
Hi @patrikhermansson! 
Can you try please latest release https://github.com/gotd/td/releases/tag/v0.26.2?

**Comment by patrikhermansson** [comment]
This fixes it! Great work.

**Comment by tdakkota** [comment]
Fixed by https://github.com/gotd/td/commit/8d82d61b16e7ea87af025712f1fdfa6a4117dcd9.
